spring:
  # https://doc.sm.ms/
  smms:
    enable: true
    authorization-code: xxx
    password: qyEF63QVT4!NwT9
    username: luna_nov

  xunfei:
    enable: true
    app-id: "e76d7d8f"
    api-secret: "990e2770b030441fbcc126c691daf5cd"
    apikey: "Y2Y2ODc2OGQyOWFjMWZhY2JkOTllMDVl"


  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    nick: LUNA
    password: xxx
    port: 465
    properties:
      mail:
        debug: false
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    username: 1173x@qq.com