name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    environment: deploy # 注意环境
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout 🛎️
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Copy apidocs
        run: |
          cp -r api-spring-boot-starter/target/apidocs api-spring-boot-starter/apidocs
          cp -r baidu-spring-boot-starter/target/apidocs baidu-spring-boot-starter/apidocs
          cp -r tencent-spring-boot-starter/target/apidocs tencent-spring-boot-starter/apidocs
          cp -r ali-spring-boot-starter/target/apidocs ali-spring-boot-starter/apidocs
          cp -r tencent-pay-spring-boot-starter/target/apidocs tencent-pay-spring-boot-starter/apidocs
          cp -r ali-pay-spring-boot-starter/target/apidocs ali-pay-spring-boot-starter/apidocs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
          GITHUB_TOKEN: ${{ secrets.SECRET_KEY }}